
EXECUTE_PROCESS(COMMAND sh ${CMAKE_CURRENT_BINARY_DIR}/merge_hni_php.sh)

if(OPENSSL_FOUND)
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*OPENSSL_FOUND\\*>//g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
else()
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*OPENSSL_FOUND\\*>/#\\*cmake_mark_OPENSSL_FOUND\\*#/g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
endif()

if(HAVE_DISPATCH_INTERVAL_FUNCTION)
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_DISPATCH_INTERVAL_FUNCTION\\*>//g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
else()
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_DISPATCH_INTERVAL_FUNCTION\\*>/#\\*cmake_mark_HAVE_DISPATCH_INTERVAL_FUNCTION\\*#/g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
endif()
