
EXECUTE_PROCESS(COMMAND sh ${CMAKE_CURRENT_BINARY_DIR}/merge_hni_php.sh)

if(HAVE_LIBEVENT_SSL_SUPPORT)
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_LIBEVENT_SSL_SUPPORT\\*>//g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
else()
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_LIBEVENT_SSL_SUPPORT\\*>/#\\*cmake_mark_HAVE_LIBEVENT_SSL_SUPPORT\\*#/g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
endif()

if(HAVE_DISPATCH_INTERVAL_FUNCTION)
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_DISPATCH_INTERVAL_FUNCTION\\*>//g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
else()
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_DISPATCH_INTERVAL_FUNCTION\\*>/#\\*cmake_mark_HAVE_DISPATCH_INTERVAL_FUNCTION\\*#/g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
endif()

if(HAVE_LIBEVENT_HTTP_SUPPORT)
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_LIBEVENT_HTTP_SUPPORT\\*>//g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
else()
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_LIBEVENT_HTTP_SUPPORT\\*>/#\\*cmake_mark_HAVE_LIBEVENT_HTTP_SUPPORT\\*#/g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
endif()

if(HAVE_LIBEVENT_DNS_SUPPORT)
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_LIBEVENT_DNS_SUPPORT\\*>//g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
else()
    EXECUTE_PROCESS(COMMAND sed -i "s/<\\*HAVE_LIBEVENT_DNS_SUPPORT\\*>/#\\*cmake_mark_HAVE_LIBEVENT_DNS_SUPPORT\\*#/g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
endif()

EXECUTE_PROCESS(COMMAND sed -i "s/<\\*.*\\*>/#\\*cmake_mark\\*#/g" ${CMAKE_CURRENT_BINARY_DIR}/${HNI_PHP_FILE})
